sonar.projectKey=cineverse-api
sonar.projectName=Cineverse API
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_bf908658b99ddb984313c1137a5d7f59cd6ea464
